# path
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="/Applications/WezTerm.app/Contents/MacOS:$PATH"
export PATH="/opt/homebrew/opt/node@22/bin:$PATH"
export PATH="/Applications/cmux.app/Contents/Resources/bin:$PATH"

# locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
