# path
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export PATH="/Applications/WezTerm.app/Contents/MacOS:$PATH"


# locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
